# Generated by Django 4.2.7 on 2025-08-05 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'emprunt")),
                ('due_date', models.DateField(verbose_name='Date de retour prévue')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('returned', 'Retourné'), ('overdue', 'En retard'), ('lost', 'Perdu')], default='active', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('librarian_notes', models.TextField(blank=True, verbose_name='Notes du bibliothécaire')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Livre')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Emprunteur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Créé'), ('extended', 'Prolongé'), ('returned', 'Retourné'), ('marked_lost', 'Marqué comme perdu'), ('renewed', 'Renouvelé')], max_length=20, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='loans.loan', verbose_name='Emprunt')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': "Historique d'emprunt",
                'verbose_name_plural': "Historiques d'emprunts",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('expiry_date', models.DateTimeField(verbose_name="Date d'expiration")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('available', 'Disponible'), ('fulfilled', 'Satisfaite'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='pending', max_length=20, verbose_name='Statut')),
                ('notified', models.BooleanField(default=False, verbose_name='Notifié')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-reserved_date'],
                'unique_together': {('book', 'user', 'status')},
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='loans_loan_borrowe_d07c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='loans_loan_due_dat_1042a5_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
    ]
